databases:
  - name: postgres
    ipAllowList: []
    databaseName: minder
    user: casey
    type: free

services:
  - type: web
    name: minder
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false