databases:
  - name: minder
    databaseName: minder
    user: casey

services:
  - type: web
    name: minder
    runtime: ruby
    buildCommand: ".bin//render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: minder
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false